# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mir_dashboard_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MirDashboardWidget(object):
    def setupUi(self, MirDashboardWidget):
        MirDashboardWidget.setObjectName("MirDashboardWidget")
        MirDashboardWidget.resize(562, 562)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MirDashboardWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(MirDashboardWidget)
        self.label_8.setStyleSheet(
            "background-color: rgb(85, 170, 255);\n"
            "color: rgb(255, 255, 255);\n"
            "padding: 2px;"
        )
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(MirDashboardWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(MirDashboardWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_5 = QtWidgets.QLabel(MirDashboardWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_10 = QtWidgets.QLabel(MirDashboardWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit = QtWidgets.QLineEdit(MirDashboardWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setStyleSheet(
            " background-color: #f2f2f2;\n"
            "color: #333; \n"
            "padding: 2px;\n"
            "border: 1px solid #ccc;\n"
            "border-radius: 2px;\n"
            "selection-color: black;\n"
            "selection-background-color: #ccc;"
        )
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(MirDashboardWidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setStyleSheet(
            " background-color: #f2f2f2;\n"
            "color: #333; \n"
            "padding: 2px;\n"
            "border: 1px solid #ccc;\n"
            "border-radius: 2px;\n"
            "selection-color: black;\n"
            "selection-background-color: #ccc;"
        )
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(MirDashboardWidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setStyleSheet(
            " background-color: #f2f2f2;\n"
            "color: #333; \n"
            "padding: 2px;\n"
            "border: 1px solid #ccc;\n"
            "border-radius: 2px;\n"
            "selection-color: black;\n"
            "selection-background-color: #ccc;"
        )
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(MirDashboardWidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setStyleSheet(
            " background-color: #f2f2f2;\n"
            "color: #333; \n"
            "padding: 2px;\n"
            "border: 1px solid #ccc;\n"
            "border-radius: 2px;\n"
            "selection-color: black;\n"
            "selection-background-color: #ccc;"
        )
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_7 = QtWidgets.QLabel(MirDashboardWidget)
        self.label_7.setStyleSheet(
            "background-color: rgb(85, 170, 255);\n"
            "color: rgb(255, 255, 255);\n"
            "padding: 2px;"
        )
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.scrollArea_mission_queue = QtWidgets.QScrollArea(MirDashboardWidget)
        self.scrollArea_mission_queue.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored
        )
        self.scrollArea_mission_queue.setWidgetResizable(True)
        self.scrollArea_mission_queue.setObjectName("scrollArea_mission_queue")
        self.scrollArea_mission_queue_widget = QtWidgets.QWidget()
        self.scrollArea_mission_queue_widget.setGeometry(QtCore.QRect(0, 0, 540, 380))
        self.scrollArea_mission_queue_widget.setObjectName(
            "scrollArea_mission_queue_widget"
        )
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.scrollArea_mission_queue_widget
        )
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_mission_queue_layout = QtWidgets.QVBoxLayout()
        self.scrollArea_mission_queue_layout.setObjectName(
            "scrollArea_mission_queue_layout"
        )
        self.verticalLayout_3.addLayout(self.scrollArea_mission_queue_layout)
        self.scrollArea_mission_queue.setWidget(self.scrollArea_mission_queue_widget)
        self.verticalLayout.addWidget(self.scrollArea_mission_queue)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MirDashboardWidget)
        QtCore.QMetaObject.connectSlotsByName(MirDashboardWidget)

    def retranslateUi(self, MirDashboardWidget):
        _translate = QtCore.QCoreApplication.translate
        MirDashboardWidget.setWindowTitle(_translate("MirDashboardWidget", "Form"))
        self.label_8.setText(_translate("MirDashboardWidget", "Robot information"))
        self.label.setText(_translate("MirDashboardWidget", "Name:"))
        self.label_2.setText(_translate("MirDashboardWidget", "IP Address:"))
        self.label_5.setText(_translate("MirDashboardWidget", "Battery:"))
        self.label_10.setText(_translate("MirDashboardWidget", "State:"))
        self.label_7.setText(_translate("MirDashboardWidget", "Mission queue"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MirDashboardWidget = QtWidgets.QWidget()
    ui = Ui_MirDashboardWidget()
    ui.setupUi(MirDashboardWidget)
    MirDashboardWidget.show()
    sys.exit(app.exec_())
