# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'station_ur_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StationUrWidget(object):
    def setupUi(self, StationUrWidget):
        StationUrWidget.setObjectName("StationUrWidget")
        StationUrWidget.resize(420, 186)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(StationUrWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(StationUrWidget)
        self.label_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding: 3px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(StationUrWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_ur_state = QtWidgets.QLineEdit(StationUrWidget)
        self.lineEdit_ur_state.setEnabled(False)
        self.lineEdit_ur_state.setStyleSheet(" background-color: #f2f2f2;\n"
"color: #333; \n"
"padding: 2px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"selection-color: black;\n"
"selection-background-color: #ccc;")
        self.lineEdit_ur_state.setObjectName("lineEdit_ur_state")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ur_state)
        self.label_4 = QtWidgets.QLabel(StationUrWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(StationUrWidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setStyleSheet(" background-color: #f2f2f2;\n"
"color: #333; \n"
"padding: 2px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"selection-color: black;\n"
"selection-background-color: #ccc;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(StationUrWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(StationUrWidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setStyleSheet(" background-color: #f2f2f2;\n"
"color: #333; \n"
"padding: 2px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"selection-color: black;\n"
"selection-background-color: #ccc;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(StationUrWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(StationUrWidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setStyleSheet(" background-color: #f2f2f2;\n"
"color: #333; \n"
"padding: 2px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"selection-color: black;\n"
"selection-background-color: #ccc;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(StationUrWidget)
        self.label_7.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding: 3px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(StationUrWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(StationUrWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(StationUrWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_5 = QtWidgets.QLineEdit(StationUrWidget)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setStyleSheet(" background-color: #f2f2f2;\n"
"color: #333; \n"
"padding: 2px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"selection-color: black;\n"
"selection-background-color: #ccc;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(StationUrWidget)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setStyleSheet(" background-color: #f2f2f2;\n"
"color: #333; \n"
"padding: 2px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"selection-color: black;\n"
"selection-background-color: #ccc;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(StationUrWidget)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setStyleSheet(" background-color: #f2f2f2;\n"
"color: #333; \n"
"padding: 2px;\n"
"border: 1px solid #ccc;\n"
"border-radius: 2px;\n"
"selection-color: black;\n"
"selection-background-color: #ccc;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(StationUrWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_pick = QtWidgets.QPushButton(StationUrWidget)
        self.pushButton_pick.setObjectName("pushButton_pick")
        self.horizontalLayout.addWidget(self.pushButton_pick)
        self.pushButton_place = QtWidgets.QPushButton(StationUrWidget)
        self.pushButton_place.setObjectName("pushButton_place")
        self.horizontalLayout.addWidget(self.pushButton_place)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(StationUrWidget)
        QtCore.QMetaObject.connectSlotsByName(StationUrWidget)

    def retranslateUi(self, StationUrWidget):
        _translate = QtCore.QCoreApplication.translate
        StationUrWidget.setWindowTitle(_translate("StationUrWidget", "Station UR Widget"))
        self.label_2.setText(_translate("StationUrWidget", "UR"))
        self.label_3.setText(_translate("StationUrWidget", "State"))
        self.label_4.setText(_translate("StationUrWidget", "Program running"))
        self.label_5.setText(_translate("StationUrWidget", "Emergency stopped"))
        self.label_6.setText(_translate("StationUrWidget", "Protective stopped"))
        self.label_7.setText(_translate("StationUrWidget", "Station"))
        self.label_8.setText(_translate("StationUrWidget", "Feed-in"))
        self.label_9.setText(_translate("StationUrWidget", "Feed-out"))
        self.label_10.setText(_translate("StationUrWidget", "State"))
        self.label.setText(_translate("StationUrWidget", "MiR :"))
        self.pushButton_pick.setText(_translate("StationUrWidget", "Pick"))
        self.pushButton_place.setText(_translate("StationUrWidget", "Place"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StationUrWidget = QtWidgets.QWidget()
    ui = Ui_StationUrWidget()
    ui.setupUi(StationUrWidget)
    StationUrWidget.show()
    sys.exit(app.exec_())
